# Use root/example as user/password credentials
version: '3.1'
services:
  mongo:
    container_name: mongo-airp0wer-server
    image: mongo
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    labels:
      - "docker-volume-backup.archive-pre=/bin/sh -c 'mongodump --username=${MONGO_ROOT_USER} --password=${MONGO_ROOT_PASSWORD} --out=/backups/mongo_db'"
      - "docker-volume-backup.stop-during-backup=stopservice"
    volumes:
      - 'backup:/backups'
      - 'mongodata:/data/db'
      - 'mongodata:/data/configdb'
    networks:
      - db
  mongo-express:
    container_name: mongo-airp0wer-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-airp0wer-server
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
    volumes:
      - 'mongodata:/data/db'
    networks:
      - db
networks:
    db:
      driver: bridge
volumes:
  mongodata:
    name: mongodata
  backup:
    name: backup
    external: true


